apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.clusterName }}
  description: EKS cluster for ${{ values.clusterName }}
spec:
  type: resource
  lifecycle: development
  system: back-stack
  owner: platform-engineers
  links:
    - url: https://console.cloud.google.com/kubernetes/clusters/details/${{ values.region }}/${{ values.clusterName }}
      title: EKS Console