---
apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    uptest.upbound.io/timeout: "2400"
    argocd.argoproj.io/sync-wave: "12"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: ${{ values.clusterName }}
spec:
  providerConfigRef:
    name: aws-provider-config 
  forProvider:
    region: ${{ values.region }}
    roleArnRef:
      name: eks-ex-cluster-role
    vpcConfig:
      - endpointPrivateAccess: false
        endpointPublicAccess: true
        subnetIdRefs:
          - name: dev-private-us-east-1a
          - name: dev-private-us-east-1b