apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: my-eks-2
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: aws-provider-config 
  forProvider:
    region: us-east-1
    roleArnRef:
      name: eks-ex-cluster-role
    vpcConfig:
      - endpointPrivateAccess: false
        endpointPublicAccess: true
        subnetIdRefs:
          - name: subnet-my-eks-1
  writeConnectionSecretToRef:
    name: my-eks-2-aws-connection-secret
    namespace: upbound-system