apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: eip-${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: aws-provider-config  # This line points to your specific ProviderConfig
  forProvider:
    region: ${{ values.region }}
    vpc: true