
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: nat-${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: aws-provider-config  # This line points to your specific ProviderConfig
  forProvider:
    region: ${{ values.region }}
    connectivityType: public
    allocationIdRef:
      name: eip-${{ values.clusterName }}
    subnetIdSelector:
      matchLabels:
        name: private-subnet-${{ values.region }}a