---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: route-${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: aws-provider-config  # This line points to your specific ProviderConfig
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdRef:
      name: igw-${{ values.clusterName }}
    region: ${{ values.region }}
    routeTableIdRef:
      name: rt-${{ values.clusterName }}
