---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: subnet-${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    name: subnet-${{ values.clusterName }}
spec:
  providerConfigRef:
    name: aws-provider-config  # This line points to your specific ProviderConfig
  forProvider:
    cidrBlock: 10.0.0.0/19
    region: ${{ values.region }}
    vpcIdRef:
      name: vpc-${{ values.clusterName }}
---

